#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 daniel g. siegel <dgsiegel@gmail.com>
# Copyright (C) 2007 Jaap A. Haitsma <jaap@haitsma.org>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

obj = bld.create_obj("gnome_doc")
obj.doc_module = "cheese"
obj.doc_entities = "legal.xml"
obj.doc_includes = ""
obj.doc_figures = "figures/cheese-screenshot.jpg figures/cheese-effects-screenshot.jpg"
obj.doc_linguas = "el es fr oc ru sv"

