#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 daniel g. siegel <dgsiegel@gnome.org>
# Copyright (C) 2007 Jaap A. Haitsma <jaap@haitsma.org>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

obj=bld.create_obj('intltool_po')
obj.appname='cheese'
