#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 daniel g. siegel <dgsiegel@gmail.com>
# Copyright (C) 2007 Jaap A. Haitsma <jaap@haitsma.org>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
import misc

env = bld.env()

install_files('PACKAGE_DATADIR', '', 'cheese-ui.xml')
install_files('PACKAGE_DATADIR', '', 'cheese.ui')
install_files('PACKAGE_DATADIR', '', 'cheese-bugreport.sh')

# process schemas.in file
obj=bld.create_obj('intltool_in')
obj.source  = 'cheese.schemas.in'
obj.destvar = 'PREFIX'
obj.subdir  = 'etc/gconf/schemas'
obj.podir   = '../po'
obj.flags   = '-s'

# process desktop.in.in file
obj = bld.create_obj('subst')
obj.source = 'cheese.desktop.in.in'
obj.target = 'cheese.desktop.in'
obj.dict = {'VERSION': env['VERSION'], 'FULL_LIBDIR': env['PACKAGE_DATADIR']}
obj.fun = misc.subst_func
obj.prio = 1 # make sure that we run before intltool_in which processes desktop.in file

# process desktop.in file
obj=bld.create_obj('intltool_in')
obj.source  = 'cheese.desktop.in'
obj.destvar = 'PREFIX'
obj.subdir  = 'share/applications'
obj.podir   = '../po'
obj.flags   = '-d'

# data/effects
install_files('PACKAGE_DATADIR', 'effects', 'effects/*.png')
install_files('PACKAGE_DATADIR', 'pixmaps', 'pixmaps/*.png')

# data/icons
for i in ["16x16", "22x22", "24x24", "32x32", "48x48"]:
	install_files('DATADIR', 'icons/hicolor/%s/apps' % i, 'icons/%s/cheese.png' % i)

install_files('DATADIR', 'icons/hicolor/scalable/apps', 'icons/scalable/cheese.svg')

# data/sounds
install_files('PACKAGE_DATADIR', 'sounds', 'sounds/shutter*.ogg')

