#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 daniel g. siegel <dgsiegel@gmail.com>
# Copyright (C) 2007 Jaap A. Haitsma <jaap@haitsma.org>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

install_files('PACKAGE_DATADIR', '', 'cheese-ui.xml')
install_files('PACKAGE_DATADIR', '', 'cheese.glade')

# process .in files with intl_tool
obj=bld.create_obj('gnome_intltool')
obj.source  = 'cheese.schemas.in'
obj.destvar = 'PREFIX'
obj.subdir  = 'etc/gconf/schemas'
obj.podir   = '../po'
obj.flags   = '-s'

obj=bld.create_obj('gnome_intltool')
obj.source  = 'cheese.desktop.in'
obj.destvar = 'PREFIX'
obj.subdir  = 'share/applications'
obj.podir   = '../po'
obj.flags   = '-d'

# data/effects
install_files('PACKAGE_DATADIR', 'effects', 'effects/*.png')

# data/icons
for i in "16x16 22x22 24x24 32x32 48x48".split():
  install_files('DATADIR', 'icons/hicolor/%s/apps' % i, 'icons/%s/cheese.png' % i)
install_files('DATADIR', 'icons/hicolor/scalable/apps', 'icons/scalable/cheese.svg')


