#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 daniel g. siegel <dgsiegel@gnome.org>
# Copyright (C) 2007 Jaap A. Haitsma <jaap@haitsma.org>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

obj = bld.create_obj('cc', 'program')
obj.find_sources_in_dirs('.') # take the sources in the current folder
obj.includes='.'
obj.uselib='''GLIB GOBJECT GIO GTK GDK
              LIBGNOMEDESKTOP GCONF GSTREAMER
              GSTREAMER_PLUGINS_BASE LIBEBOOK
              CAIRO DBUS DBUSGLIB HAL PANGOCAIRO LIBRSVG'''

obj.target='cheese'
obj.add_dbus_file('cheese-dbus-infos.xml', 'cheese_dbus', 'glib-server')
