#!/usr/bin/env make

include toc2.make
EFFECTS = *.png

package.dist_files += $(EFFECTS)
package.install.package_data.dest := $(prefix)/share/$(package.name)/effects
package.install.package_data += $(EFFECTS)
 
